#app-level-configs
spring.application.name=ecommerce-app
server.port=8080

#POSTGRESQL
spring.datasource.url = jdbc:postgresql://localhost:5434/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Champ@1911
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#SPRING SECURITY
server.servlet.session.cookie.same-site=strict
logging.level.org.springframework.security=DEBUG

#BASIC AUTH
#spring.security.user.name=karan
#spring.security.user.password=12345678
#JWT token related configurations: get the JWT_SECRET from the env. variable with expiration
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

#pagination-configs - to load these values in spring, we need a component class linked with these values
pagination.default-page=0
pagination.default-size=10
pagination.max-page-size=50

#CACHING
spring.cache,type= redis
spring.redis.host= ${REDIS_HOST}
spring.redis.port= ${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}
spring.redis.ssl = true
spring.redis.timeout=6000
spring.cache.redis.time-to-live=600000 // 10 minutes
